// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/RSODA/todo-go/internal/repo.Repo -o repo_minimock.go -n RepoMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/RSODA/todo-go/internal/models"
	"github.com/gojuno/minimock/v3"
)

// RepoMock implements mm_repo.Repo
type RepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, b *models.TODO) (tp1 *models.TODO, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, b *models.TODO)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mRepoMockCreate

	funcDelete          func(ctx context.Context, id int64) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, id int64)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mRepoMockDelete

	funcGet          func(ctx context.Context, id int64) (tp1 *models.TODO, err error)
	funcGetOrigin    string
	inspectFuncGet   func(ctx context.Context, id int64)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mRepoMockGet

	funcUpdateTask          func(ctx context.Context, m *models.UpdateTaskRequest) (err error)
	funcUpdateTaskOrigin    string
	inspectFuncUpdateTask   func(ctx context.Context, m *models.UpdateTaskRequest)
	afterUpdateTaskCounter  uint64
	beforeUpdateTaskCounter uint64
	UpdateTaskMock          mRepoMockUpdateTask
}

// NewRepoMock returns a mock for mm_repo.Repo
func NewRepoMock(t minimock.Tester) *RepoMock {
	m := &RepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mRepoMockCreate{mock: m}
	m.CreateMock.callArgs = []*RepoMockCreateParams{}

	m.DeleteMock = mRepoMockDelete{mock: m}
	m.DeleteMock.callArgs = []*RepoMockDeleteParams{}

	m.GetMock = mRepoMockGet{mock: m}
	m.GetMock.callArgs = []*RepoMockGetParams{}

	m.UpdateTaskMock = mRepoMockUpdateTask{mock: m}
	m.UpdateTaskMock.callArgs = []*RepoMockUpdateTaskParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRepoMockCreate struct {
	optional           bool
	mock               *RepoMock
	defaultExpectation *RepoMockCreateExpectation
	expectations       []*RepoMockCreateExpectation

	callArgs []*RepoMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepoMockCreateExpectation specifies expectation struct of the Repo.Create
type RepoMockCreateExpectation struct {
	mock               *RepoMock
	params             *RepoMockCreateParams
	paramPtrs          *RepoMockCreateParamPtrs
	expectationOrigins RepoMockCreateExpectationOrigins
	results            *RepoMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// RepoMockCreateParams contains parameters of the Repo.Create
type RepoMockCreateParams struct {
	ctx context.Context
	b   *models.TODO
}

// RepoMockCreateParamPtrs contains pointers to parameters of the Repo.Create
type RepoMockCreateParamPtrs struct {
	ctx *context.Context
	b   **models.TODO
}

// RepoMockCreateResults contains results of the Repo.Create
type RepoMockCreateResults struct {
	tp1 *models.TODO
	err error
}

// RepoMockCreateOrigins contains origins of expectations of the Repo.Create
type RepoMockCreateExpectationOrigins struct {
	origin    string
	originCtx string
	originB   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mRepoMockCreate) Optional() *mRepoMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for Repo.Create
func (mmCreate *mRepoMockCreate) Expect(ctx context.Context, b *models.TODO) *mRepoMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RepoMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RepoMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("RepoMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &RepoMockCreateParams{ctx, b}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for Repo.Create
func (mmCreate *mRepoMockCreate) ExpectCtxParam1(ctx context.Context) *mRepoMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RepoMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RepoMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("RepoMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &RepoMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectBParam2 sets up expected param b for Repo.Create
func (mmCreate *mRepoMockCreate) ExpectBParam2(b *models.TODO) *mRepoMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RepoMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RepoMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("RepoMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &RepoMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.b = &b
	mmCreate.defaultExpectation.expectationOrigins.originB = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the Repo.Create
func (mmCreate *mRepoMockCreate) Inspect(f func(ctx context.Context, b *models.TODO)) *mRepoMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for RepoMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by Repo.Create
func (mmCreate *mRepoMockCreate) Return(tp1 *models.TODO, err error) *RepoMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RepoMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RepoMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &RepoMockCreateResults{tp1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the Repo.Create method
func (mmCreate *mRepoMockCreate) Set(f func(ctx context.Context, b *models.TODO) (tp1 *models.TODO, err error)) *RepoMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the Repo.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the Repo.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the Repo.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mRepoMockCreate) When(ctx context.Context, b *models.TODO) *RepoMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RepoMock.Create mock is already set by Set")
	}

	expectation := &RepoMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &RepoMockCreateParams{ctx, b},
		expectationOrigins: RepoMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up Repo.Create return parameters for the expectation previously defined by the When method
func (e *RepoMockCreateExpectation) Then(tp1 *models.TODO, err error) *RepoMock {
	e.results = &RepoMockCreateResults{tp1, err}
	return e.mock
}

// Times sets number of times Repo.Create should be invoked
func (mmCreate *mRepoMockCreate) Times(n uint64) *mRepoMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of RepoMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mRepoMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_repo.Repo
func (mmCreate *RepoMock) Create(ctx context.Context, b *models.TODO) (tp1 *models.TODO, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, b)
	}

	mm_params := RepoMockCreateParams{ctx, b}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.tp1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := RepoMockCreateParams{ctx, b}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("RepoMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.b != nil && !minimock.Equal(*mm_want_ptrs.b, mm_got.b) {
				mmCreate.t.Errorf("RepoMock.Create got unexpected parameter b, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originB, *mm_want_ptrs.b, mm_got.b, minimock.Diff(*mm_want_ptrs.b, mm_got.b))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("RepoMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the RepoMock.Create")
		}
		return (*mm_results).tp1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, b)
	}
	mmCreate.t.Fatalf("Unexpected call to RepoMock.Create. %v %v", ctx, b)
	return
}

// CreateAfterCounter returns a count of finished RepoMock.Create invocations
func (mmCreate *RepoMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of RepoMock.Create invocations
func (mmCreate *RepoMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mRepoMockCreate) Calls() []*RepoMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*RepoMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *RepoMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepoMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepoMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to RepoMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to RepoMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mRepoMockDelete struct {
	optional           bool
	mock               *RepoMock
	defaultExpectation *RepoMockDeleteExpectation
	expectations       []*RepoMockDeleteExpectation

	callArgs []*RepoMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepoMockDeleteExpectation specifies expectation struct of the Repo.Delete
type RepoMockDeleteExpectation struct {
	mock               *RepoMock
	params             *RepoMockDeleteParams
	paramPtrs          *RepoMockDeleteParamPtrs
	expectationOrigins RepoMockDeleteExpectationOrigins
	results            *RepoMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// RepoMockDeleteParams contains parameters of the Repo.Delete
type RepoMockDeleteParams struct {
	ctx context.Context
	id  int64
}

// RepoMockDeleteParamPtrs contains pointers to parameters of the Repo.Delete
type RepoMockDeleteParamPtrs struct {
	ctx *context.Context
	id  *int64
}

// RepoMockDeleteResults contains results of the Repo.Delete
type RepoMockDeleteResults struct {
	err error
}

// RepoMockDeleteOrigins contains origins of expectations of the Repo.Delete
type RepoMockDeleteExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mRepoMockDelete) Optional() *mRepoMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for Repo.Delete
func (mmDelete *mRepoMockDelete) Expect(ctx context.Context, id int64) *mRepoMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("RepoMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &RepoMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("RepoMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &RepoMockDeleteParams{ctx, id}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for Repo.Delete
func (mmDelete *mRepoMockDelete) ExpectCtxParam1(ctx context.Context) *mRepoMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("RepoMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &RepoMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("RepoMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &RepoMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectIdParam2 sets up expected param id for Repo.Delete
func (mmDelete *mRepoMockDelete) ExpectIdParam2(id int64) *mRepoMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("RepoMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &RepoMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("RepoMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &RepoMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.id = &id
	mmDelete.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the Repo.Delete
func (mmDelete *mRepoMockDelete) Inspect(f func(ctx context.Context, id int64)) *mRepoMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for RepoMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by Repo.Delete
func (mmDelete *mRepoMockDelete) Return(err error) *RepoMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("RepoMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &RepoMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &RepoMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the Repo.Delete method
func (mmDelete *mRepoMockDelete) Set(f func(ctx context.Context, id int64) (err error)) *RepoMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the Repo.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the Repo.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the Repo.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mRepoMockDelete) When(ctx context.Context, id int64) *RepoMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("RepoMock.Delete mock is already set by Set")
	}

	expectation := &RepoMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &RepoMockDeleteParams{ctx, id},
		expectationOrigins: RepoMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up Repo.Delete return parameters for the expectation previously defined by the When method
func (e *RepoMockDeleteExpectation) Then(err error) *RepoMock {
	e.results = &RepoMockDeleteResults{err}
	return e.mock
}

// Times sets number of times Repo.Delete should be invoked
func (mmDelete *mRepoMockDelete) Times(n uint64) *mRepoMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of RepoMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mRepoMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements mm_repo.Repo
func (mmDelete *RepoMock) Delete(ctx context.Context, id int64) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, id)
	}

	mm_params := RepoMockDeleteParams{ctx, id}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := RepoMockDeleteParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("RepoMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDelete.t.Errorf("RepoMock.Delete got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("RepoMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the RepoMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, id)
	}
	mmDelete.t.Fatalf("Unexpected call to RepoMock.Delete. %v %v", ctx, id)
	return
}

// DeleteAfterCounter returns a count of finished RepoMock.Delete invocations
func (mmDelete *RepoMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of RepoMock.Delete invocations
func (mmDelete *RepoMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mRepoMockDelete) Calls() []*RepoMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*RepoMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *RepoMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepoMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepoMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to RepoMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to RepoMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mRepoMockGet struct {
	optional           bool
	mock               *RepoMock
	defaultExpectation *RepoMockGetExpectation
	expectations       []*RepoMockGetExpectation

	callArgs []*RepoMockGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepoMockGetExpectation specifies expectation struct of the Repo.Get
type RepoMockGetExpectation struct {
	mock               *RepoMock
	params             *RepoMockGetParams
	paramPtrs          *RepoMockGetParamPtrs
	expectationOrigins RepoMockGetExpectationOrigins
	results            *RepoMockGetResults
	returnOrigin       string
	Counter            uint64
}

// RepoMockGetParams contains parameters of the Repo.Get
type RepoMockGetParams struct {
	ctx context.Context
	id  int64
}

// RepoMockGetParamPtrs contains pointers to parameters of the Repo.Get
type RepoMockGetParamPtrs struct {
	ctx *context.Context
	id  *int64
}

// RepoMockGetResults contains results of the Repo.Get
type RepoMockGetResults struct {
	tp1 *models.TODO
	err error
}

// RepoMockGetOrigins contains origins of expectations of the Repo.Get
type RepoMockGetExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGet *mRepoMockGet) Optional() *mRepoMockGet {
	mmGet.optional = true
	return mmGet
}

// Expect sets up expected params for Repo.Get
func (mmGet *mRepoMockGet) Expect(ctx context.Context, id int64) *mRepoMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("RepoMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &RepoMockGetExpectation{}
	}

	if mmGet.defaultExpectation.paramPtrs != nil {
		mmGet.mock.t.Fatalf("RepoMock.Get mock is already set by ExpectParams functions")
	}

	mmGet.defaultExpectation.params = &RepoMockGetParams{ctx, id}
	mmGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// ExpectCtxParam1 sets up expected param ctx for Repo.Get
func (mmGet *mRepoMockGet) ExpectCtxParam1(ctx context.Context) *mRepoMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("RepoMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &RepoMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("RepoMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &RepoMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.ctx = &ctx
	mmGet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGet
}

// ExpectIdParam2 sets up expected param id for Repo.Get
func (mmGet *mRepoMockGet) ExpectIdParam2(id int64) *mRepoMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("RepoMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &RepoMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("RepoMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &RepoMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.id = &id
	mmGet.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the Repo.Get
func (mmGet *mRepoMockGet) Inspect(f func(ctx context.Context, id int64)) *mRepoMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for RepoMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by Repo.Get
func (mmGet *mRepoMockGet) Return(tp1 *models.TODO, err error) *RepoMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("RepoMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &RepoMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &RepoMockGetResults{tp1, err}
	mmGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// Set uses given function f to mock the Repo.Get method
func (mmGet *mRepoMockGet) Set(f func(ctx context.Context, id int64) (tp1 *models.TODO, err error)) *RepoMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the Repo.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the Repo.Get method")
	}

	mmGet.mock.funcGet = f
	mmGet.mock.funcGetOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// When sets expectation for the Repo.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mRepoMockGet) When(ctx context.Context, id int64) *RepoMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("RepoMock.Get mock is already set by Set")
	}

	expectation := &RepoMockGetExpectation{
		mock:               mmGet.mock,
		params:             &RepoMockGetParams{ctx, id},
		expectationOrigins: RepoMockGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up Repo.Get return parameters for the expectation previously defined by the When method
func (e *RepoMockGetExpectation) Then(tp1 *models.TODO, err error) *RepoMock {
	e.results = &RepoMockGetResults{tp1, err}
	return e.mock
}

// Times sets number of times Repo.Get should be invoked
func (mmGet *mRepoMockGet) Times(n uint64) *mRepoMockGet {
	if n == 0 {
		mmGet.mock.t.Fatalf("Times of RepoMock.Get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGet.expectedInvocations, n)
	mmGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGet
}

func (mmGet *mRepoMockGet) invocationsDone() bool {
	if len(mmGet.expectations) == 0 && mmGet.defaultExpectation == nil && mmGet.mock.funcGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGet.mock.afterGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Get implements mm_repo.Repo
func (mmGet *RepoMock) Get(ctx context.Context, id int64) (tp1 *models.TODO, err error) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	mmGet.t.Helper()

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(ctx, id)
	}

	mm_params := RepoMockGetParams{ctx, id}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.tp1, e.results.err
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_want_ptrs := mmGet.GetMock.defaultExpectation.paramPtrs

		mm_got := RepoMockGetParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGet.t.Errorf("RepoMock.Get got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGet.t.Errorf("RepoMock.Get got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("RepoMock.Get got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGet.GetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the RepoMock.Get")
		}
		return (*mm_results).tp1, (*mm_results).err
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(ctx, id)
	}
	mmGet.t.Fatalf("Unexpected call to RepoMock.Get. %v %v", ctx, id)
	return
}

// GetAfterCounter returns a count of finished RepoMock.Get invocations
func (mmGet *RepoMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of RepoMock.Get invocations
func (mmGet *RepoMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mRepoMockGet) Calls() []*RepoMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*RepoMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockGetDone() bool {
	if m.GetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMock.invocationsDone()
}

// MinimockGetInspect logs each unmet expectation
func (m *RepoMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.Get at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCounter := mm_atomic.LoadUint64(&m.afterGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && afterGetCounter < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepoMock.Get at\n%s", m.GetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepoMock.Get at\n%s with params: %#v", m.GetMock.defaultExpectation.expectationOrigins.origin, *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && afterGetCounter < 1 {
		m.t.Errorf("Expected call to RepoMock.Get at\n%s", m.funcGetOrigin)
	}

	if !m.GetMock.invocationsDone() && afterGetCounter > 0 {
		m.t.Errorf("Expected %d calls to RepoMock.Get at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMock.expectedInvocations), m.GetMock.expectedInvocationsOrigin, afterGetCounter)
	}
}

type mRepoMockUpdateTask struct {
	optional           bool
	mock               *RepoMock
	defaultExpectation *RepoMockUpdateTaskExpectation
	expectations       []*RepoMockUpdateTaskExpectation

	callArgs []*RepoMockUpdateTaskParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepoMockUpdateTaskExpectation specifies expectation struct of the Repo.UpdateTask
type RepoMockUpdateTaskExpectation struct {
	mock               *RepoMock
	params             *RepoMockUpdateTaskParams
	paramPtrs          *RepoMockUpdateTaskParamPtrs
	expectationOrigins RepoMockUpdateTaskExpectationOrigins
	results            *RepoMockUpdateTaskResults
	returnOrigin       string
	Counter            uint64
}

// RepoMockUpdateTaskParams contains parameters of the Repo.UpdateTask
type RepoMockUpdateTaskParams struct {
	ctx context.Context
	m   *models.UpdateTaskRequest
}

// RepoMockUpdateTaskParamPtrs contains pointers to parameters of the Repo.UpdateTask
type RepoMockUpdateTaskParamPtrs struct {
	ctx *context.Context
	m   **models.UpdateTaskRequest
}

// RepoMockUpdateTaskResults contains results of the Repo.UpdateTask
type RepoMockUpdateTaskResults struct {
	err error
}

// RepoMockUpdateTaskOrigins contains origins of expectations of the Repo.UpdateTask
type RepoMockUpdateTaskExpectationOrigins struct {
	origin    string
	originCtx string
	originM   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateTask *mRepoMockUpdateTask) Optional() *mRepoMockUpdateTask {
	mmUpdateTask.optional = true
	return mmUpdateTask
}

// Expect sets up expected params for Repo.UpdateTask
func (mmUpdateTask *mRepoMockUpdateTask) Expect(ctx context.Context, m *models.UpdateTaskRequest) *mRepoMockUpdateTask {
	if mmUpdateTask.mock.funcUpdateTask != nil {
		mmUpdateTask.mock.t.Fatalf("RepoMock.UpdateTask mock is already set by Set")
	}

	if mmUpdateTask.defaultExpectation == nil {
		mmUpdateTask.defaultExpectation = &RepoMockUpdateTaskExpectation{}
	}

	if mmUpdateTask.defaultExpectation.paramPtrs != nil {
		mmUpdateTask.mock.t.Fatalf("RepoMock.UpdateTask mock is already set by ExpectParams functions")
	}

	mmUpdateTask.defaultExpectation.params = &RepoMockUpdateTaskParams{ctx, m}
	mmUpdateTask.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateTask.expectations {
		if minimock.Equal(e.params, mmUpdateTask.defaultExpectation.params) {
			mmUpdateTask.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateTask.defaultExpectation.params)
		}
	}

	return mmUpdateTask
}

// ExpectCtxParam1 sets up expected param ctx for Repo.UpdateTask
func (mmUpdateTask *mRepoMockUpdateTask) ExpectCtxParam1(ctx context.Context) *mRepoMockUpdateTask {
	if mmUpdateTask.mock.funcUpdateTask != nil {
		mmUpdateTask.mock.t.Fatalf("RepoMock.UpdateTask mock is already set by Set")
	}

	if mmUpdateTask.defaultExpectation == nil {
		mmUpdateTask.defaultExpectation = &RepoMockUpdateTaskExpectation{}
	}

	if mmUpdateTask.defaultExpectation.params != nil {
		mmUpdateTask.mock.t.Fatalf("RepoMock.UpdateTask mock is already set by Expect")
	}

	if mmUpdateTask.defaultExpectation.paramPtrs == nil {
		mmUpdateTask.defaultExpectation.paramPtrs = &RepoMockUpdateTaskParamPtrs{}
	}
	mmUpdateTask.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateTask.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateTask
}

// ExpectMParam2 sets up expected param m for Repo.UpdateTask
func (mmUpdateTask *mRepoMockUpdateTask) ExpectMParam2(m *models.UpdateTaskRequest) *mRepoMockUpdateTask {
	if mmUpdateTask.mock.funcUpdateTask != nil {
		mmUpdateTask.mock.t.Fatalf("RepoMock.UpdateTask mock is already set by Set")
	}

	if mmUpdateTask.defaultExpectation == nil {
		mmUpdateTask.defaultExpectation = &RepoMockUpdateTaskExpectation{}
	}

	if mmUpdateTask.defaultExpectation.params != nil {
		mmUpdateTask.mock.t.Fatalf("RepoMock.UpdateTask mock is already set by Expect")
	}

	if mmUpdateTask.defaultExpectation.paramPtrs == nil {
		mmUpdateTask.defaultExpectation.paramPtrs = &RepoMockUpdateTaskParamPtrs{}
	}
	mmUpdateTask.defaultExpectation.paramPtrs.m = &m
	mmUpdateTask.defaultExpectation.expectationOrigins.originM = minimock.CallerInfo(1)

	return mmUpdateTask
}

// Inspect accepts an inspector function that has same arguments as the Repo.UpdateTask
func (mmUpdateTask *mRepoMockUpdateTask) Inspect(f func(ctx context.Context, m *models.UpdateTaskRequest)) *mRepoMockUpdateTask {
	if mmUpdateTask.mock.inspectFuncUpdateTask != nil {
		mmUpdateTask.mock.t.Fatalf("Inspect function is already set for RepoMock.UpdateTask")
	}

	mmUpdateTask.mock.inspectFuncUpdateTask = f

	return mmUpdateTask
}

// Return sets up results that will be returned by Repo.UpdateTask
func (mmUpdateTask *mRepoMockUpdateTask) Return(err error) *RepoMock {
	if mmUpdateTask.mock.funcUpdateTask != nil {
		mmUpdateTask.mock.t.Fatalf("RepoMock.UpdateTask mock is already set by Set")
	}

	if mmUpdateTask.defaultExpectation == nil {
		mmUpdateTask.defaultExpectation = &RepoMockUpdateTaskExpectation{mock: mmUpdateTask.mock}
	}
	mmUpdateTask.defaultExpectation.results = &RepoMockUpdateTaskResults{err}
	mmUpdateTask.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateTask.mock
}

// Set uses given function f to mock the Repo.UpdateTask method
func (mmUpdateTask *mRepoMockUpdateTask) Set(f func(ctx context.Context, m *models.UpdateTaskRequest) (err error)) *RepoMock {
	if mmUpdateTask.defaultExpectation != nil {
		mmUpdateTask.mock.t.Fatalf("Default expectation is already set for the Repo.UpdateTask method")
	}

	if len(mmUpdateTask.expectations) > 0 {
		mmUpdateTask.mock.t.Fatalf("Some expectations are already set for the Repo.UpdateTask method")
	}

	mmUpdateTask.mock.funcUpdateTask = f
	mmUpdateTask.mock.funcUpdateTaskOrigin = minimock.CallerInfo(1)
	return mmUpdateTask.mock
}

// When sets expectation for the Repo.UpdateTask which will trigger the result defined by the following
// Then helper
func (mmUpdateTask *mRepoMockUpdateTask) When(ctx context.Context, m *models.UpdateTaskRequest) *RepoMockUpdateTaskExpectation {
	if mmUpdateTask.mock.funcUpdateTask != nil {
		mmUpdateTask.mock.t.Fatalf("RepoMock.UpdateTask mock is already set by Set")
	}

	expectation := &RepoMockUpdateTaskExpectation{
		mock:               mmUpdateTask.mock,
		params:             &RepoMockUpdateTaskParams{ctx, m},
		expectationOrigins: RepoMockUpdateTaskExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateTask.expectations = append(mmUpdateTask.expectations, expectation)
	return expectation
}

// Then sets up Repo.UpdateTask return parameters for the expectation previously defined by the When method
func (e *RepoMockUpdateTaskExpectation) Then(err error) *RepoMock {
	e.results = &RepoMockUpdateTaskResults{err}
	return e.mock
}

// Times sets number of times Repo.UpdateTask should be invoked
func (mmUpdateTask *mRepoMockUpdateTask) Times(n uint64) *mRepoMockUpdateTask {
	if n == 0 {
		mmUpdateTask.mock.t.Fatalf("Times of RepoMock.UpdateTask mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateTask.expectedInvocations, n)
	mmUpdateTask.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateTask
}

func (mmUpdateTask *mRepoMockUpdateTask) invocationsDone() bool {
	if len(mmUpdateTask.expectations) == 0 && mmUpdateTask.defaultExpectation == nil && mmUpdateTask.mock.funcUpdateTask == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateTask.mock.afterUpdateTaskCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateTask.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateTask implements mm_repo.Repo
func (mmUpdateTask *RepoMock) UpdateTask(ctx context.Context, m *models.UpdateTaskRequest) (err error) {
	mm_atomic.AddUint64(&mmUpdateTask.beforeUpdateTaskCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateTask.afterUpdateTaskCounter, 1)

	mmUpdateTask.t.Helper()

	if mmUpdateTask.inspectFuncUpdateTask != nil {
		mmUpdateTask.inspectFuncUpdateTask(ctx, m)
	}

	mm_params := RepoMockUpdateTaskParams{ctx, m}

	// Record call args
	mmUpdateTask.UpdateTaskMock.mutex.Lock()
	mmUpdateTask.UpdateTaskMock.callArgs = append(mmUpdateTask.UpdateTaskMock.callArgs, &mm_params)
	mmUpdateTask.UpdateTaskMock.mutex.Unlock()

	for _, e := range mmUpdateTask.UpdateTaskMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateTask.UpdateTaskMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateTask.UpdateTaskMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateTask.UpdateTaskMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateTask.UpdateTaskMock.defaultExpectation.paramPtrs

		mm_got := RepoMockUpdateTaskParams{ctx, m}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateTask.t.Errorf("RepoMock.UpdateTask got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateTask.UpdateTaskMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.m != nil && !minimock.Equal(*mm_want_ptrs.m, mm_got.m) {
				mmUpdateTask.t.Errorf("RepoMock.UpdateTask got unexpected parameter m, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateTask.UpdateTaskMock.defaultExpectation.expectationOrigins.originM, *mm_want_ptrs.m, mm_got.m, minimock.Diff(*mm_want_ptrs.m, mm_got.m))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateTask.t.Errorf("RepoMock.UpdateTask got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateTask.UpdateTaskMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateTask.UpdateTaskMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateTask.t.Fatal("No results are set for the RepoMock.UpdateTask")
		}
		return (*mm_results).err
	}
	if mmUpdateTask.funcUpdateTask != nil {
		return mmUpdateTask.funcUpdateTask(ctx, m)
	}
	mmUpdateTask.t.Fatalf("Unexpected call to RepoMock.UpdateTask. %v %v", ctx, m)
	return
}

// UpdateTaskAfterCounter returns a count of finished RepoMock.UpdateTask invocations
func (mmUpdateTask *RepoMock) UpdateTaskAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateTask.afterUpdateTaskCounter)
}

// UpdateTaskBeforeCounter returns a count of RepoMock.UpdateTask invocations
func (mmUpdateTask *RepoMock) UpdateTaskBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateTask.beforeUpdateTaskCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.UpdateTask.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateTask *mRepoMockUpdateTask) Calls() []*RepoMockUpdateTaskParams {
	mmUpdateTask.mutex.RLock()

	argCopy := make([]*RepoMockUpdateTaskParams, len(mmUpdateTask.callArgs))
	copy(argCopy, mmUpdateTask.callArgs)

	mmUpdateTask.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateTaskDone returns true if the count of the UpdateTask invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockUpdateTaskDone() bool {
	if m.UpdateTaskMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateTaskMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateTaskMock.invocationsDone()
}

// MinimockUpdateTaskInspect logs each unmet expectation
func (m *RepoMock) MinimockUpdateTaskInspect() {
	for _, e := range m.UpdateTaskMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.UpdateTask at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateTaskCounter := mm_atomic.LoadUint64(&m.afterUpdateTaskCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateTaskMock.defaultExpectation != nil && afterUpdateTaskCounter < 1 {
		if m.UpdateTaskMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepoMock.UpdateTask at\n%s", m.UpdateTaskMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepoMock.UpdateTask at\n%s with params: %#v", m.UpdateTaskMock.defaultExpectation.expectationOrigins.origin, *m.UpdateTaskMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateTask != nil && afterUpdateTaskCounter < 1 {
		m.t.Errorf("Expected call to RepoMock.UpdateTask at\n%s", m.funcUpdateTaskOrigin)
	}

	if !m.UpdateTaskMock.invocationsDone() && afterUpdateTaskCounter > 0 {
		m.t.Errorf("Expected %d calls to RepoMock.UpdateTask at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateTaskMock.expectedInvocations), m.UpdateTaskMock.expectedInvocationsOrigin, afterUpdateTaskCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockDeleteInspect()

			m.MinimockGetInspect()

			m.MinimockUpdateTaskInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockDeleteDone() &&
		m.MinimockGetDone() &&
		m.MinimockUpdateTaskDone()
}
